apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-app-config
  namespace: default
  labels:
    app: spring-app
data:
  SPRING_KAFKA_CONSUMER_BOOTSTRAP_SERVERS: "broker-service:9092"
  SPRING_KAFKA_CONSUMER_GROUP_ID: "myGroup"
  SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET: "earliest"
  SPRING_KAFKA_CONSUMER_KEY_DESERIALIZER: "org.apache.kafka.common.serialization.StringDeserializer"
  SPRING_KAFKA_CONSUMER_VALUE_DESERIALIZER: "org.apache.kafka.common.serialization.StringDeserializer"
  SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS: "broker-service:9092"
  SPRING_KAFKA_PRODUCER_KEY_SERIALIZER: "org.apache.kafka.common.serialization.StringSerializer"
  SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER: "org.apache.kafka.common.serialization.StringSerializer"
